name: Upload code scanning results to Threadfix
description: Get code scanning results from GitHub and push them to your Threadfix application
branding:
  icon: 'award'
  color: 'green'
runs:
  using: "composite"
  steps:
    - name: Get code scanning alerts
      run: gh api repos/${{github.repository}}/code-scanning/alerts --paginate | jq --slurp 'flatten' > ./input_file.json
      shell: bash
      env:
         GITHUB_TOKEN: ${{inputs.GITHUB_TOKEN}}
    - name: Validate file 
      run : cat input_file.json | grep "number" >/dev/null && echo "got data!" || exit 1; 
      shell: bash
    - name: Convert to Threadfix file
      run: python ${{github.action_path}}/sarif_converter.py input_file.json output_file.threadfix
      shell: bash
    - name: Test instance connection
      run: |
            curl --location --request GET '${{inputs.TFIX_INSTANCE_URL}}/threadfix/rest/latest/applications/${{inputs.TFIX_APP_ID}}' \
            --header 'Authorization: APIKEY ${{inputs.TFIX_API_KEY}}' \
      shell: bash
    - name: Push to threadfix
      run: |
            curl --location --request POST '${{inputs.TFIX_INSTANCE_URL}}/threadfix/rest/latest/applications/${{inputs.TFIX_APP_ID}}/upload' \
            --header 'Accept: application/json' \
            --header 'Authorization: APIKEY ${{inputs.TFIX_API_KEY}}' \
            --form 'file=@"output_file.threadfix"'
      shell: bash
